### ISSUE TITLE
Admins shouldn't be able to mark other admins as spammers

### ISSUE THREAD

**Issue by KyrneDev** [FriendsOfFlarum/spamblock#1]
We generally need to think about who is allowed to mark who.

**Comment by jordanjay29** [comment]
IMHO, anyone with a group should be safe. This is the same logic Akismet uses to screen posts for spam as well.

**Comment by dsevillamartin** [comment]
If I use anyone with a group, forums that use default groups or where everyone has a group to differentiate wouldn't be able to mark users as spammers...

How about this: if user **can** spamblock, then they **can't** be marked as spammer.

**Comment by jordanjay29** [comment]
Seems like a reasonable compromise.
